var AppConstants = {
  CLICK_UP: "CLICK_UP",
  CLICK_DOWN: "CLICK_DOWN",
  UPDATE_CURRENT_WORLD: "UPDATE_CURRENT_WORLD",
  INITIALIZE: "INITIALIZE",
  ADD_MASTER: "ADD_MASTER",
  ADD_APPRENTICE: "ADD_APPRENTICE"
};

module.exports = AppConstants;
